title:            Thomas' blog
description:      Engineer, Space Lover, Tea Drinker
created:          Orbited
url:

# Settings for reading time
reading_time:     true
words_per_minute: 200

# Disqus ID
disqus: lord-nazdar-blog

# Owner/author information
owner:
  name:           Thomas Poulet
  avatar:         site/mountain.jpg
  bio:            Engineer, Space Lover, Tea Drinker
  email:          
  # Put the full urls
  twitter:        https://twitter.com/Lord_Nazdar
  # facebook:       
  github:         https://github.com/Lord-Nazdar
  # stackexchange:  
  linkedin:       https://www.linkedin.com/in/thomas-poulet
  # instagram:      
  # flickr:         
  # tumblr:         
  # google_plus:    


# Analytics and webmaster tools stuff goes here
# google_analytics: 
# google_verify:    
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify:      

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:       Europe/London
future:         true
highlighter:    rouge
markdown:       kramdown

plugins:
  - jekyll-watch
  - jekyll-paginate

paginate: 7

sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

include: [".htaccess"]
exclude: ["LICENSE", "README.md"]

